Repository OoTRandomizer/OoT-Randomizer, pull requests merged in 2021-07, with the labels that each got.

#1321 Update readme for pj64 v3.0
  README.md
Labels: trivial

#1315 Split on last dot in Patch filename for output files
  Main.py
Labels: Component: Randomizer Core

#1316 Custom Music: Follow Symbolic Links
  Music.py
Labels: Component: Misc

#1312 Make both 2h swords conditionally foolish
  World.py
Labels: Component: Hints

#1309 Properly handle 3.x prior to 3.6
  Gui.py
Labels: Component: Misc

#1292 Add message in place of tricks list when the list is hidden by logic setting
  GUI/src/app/pages/generator/generator.component.html
  SettingsList.py
  data/settings_mapping.json
Labels: Component: GUI/Website
