Repository OoTRandomizer/OoT-Randomizer, pull requests merged in 2022-09, with the labels that each got.

#1687 Elaborate logic_man_on_roof description
  SettingsList.py
Labels: trivial, Component: Misc

#1690 Fix potion model patching when reverting to the vanilla color
  Cosmetics.py
Labels: bug, Component: Patching

#1694 Don't list non-required effective starting items in playthrough
  Main.py
Labels: bug, Component: Randomizer Core

#1700 Document ammo count fields used for MW queue size
  Notes/extra-save-data.md
Labels: Component: Misc

#1709 Fix error allowing hinted WoTH ZL
  data/Hints/tournament_test_woth.json
Labels: Component: Hints

#1666 Dual hint revision
  HintList.py
Labels: enhancement, Component: Hints

#1701 Bugfix for visibility toggle bug (GUI)
  GUI/src/app/pages/generator/generator.component.ts
Labels: Component: GUI/Website

#1704 Version Refactor
  GUI/electron/src/preload.ts
  GUI/src/app/@theme/components/footer/footer.component.ts
  GUI/src/app/providers/GUIGlobal.ts
  Rom.py
  Utils.py
  version.py
Labels: Component: GUI/Website, Component: Misc
