Repository OoTRandomizer/OoT-Randomizer, pull requests merged in 2022-11, with the labels that each got.

#1753 Fix skull house hints being shuffled
  Messages.py
Labels: bug, Component: Hints

#1754 Fix electron use of python in release mode
  GUI/electron/src/modules/generator.js
  GUI/electron/src/preload.ts
Labels: bug, Component: GUI/Website

#1756 Reset frog sometimes hints
  data/presets_default.json
Labels: Component: Hints

#1758 update camc to randomize size and texture for s6
  data/presets_default.json
Labels: Component: Presets

#1787 Extremely huge bug fix in SettingsList.py
  SettingsList.py
Labels: trivial
